Added file sum of triplet in C
TesseractCoding/NeoAlgo pull request #658
Opened 2020-08-21 10:21 UTC by akanksha-saini

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?)

Yes.

### Description

Program in C to print all triplets of numbers which sum to target.
For example
input:
9
5 7 9 1 2 4 6 8 3
10
output:
1, 2 and 7
1, 3 and 6
1, 4 and 5
2, 3 and 5

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#585

2020-08-21 12:02 UTC, iamrajiv requested changes

2020-08-21 12:02 UTC, iamrajiv commented on C/cp/sum of triplet.c
> +/*Take as input N, the size of array. Take N more inputs and store that in an array. Take as input �target�, a number. Write a function which prints all triplets of numbers which sum to target.
@akanksha-saini add comments after this `/*`

2020-08-21 12:02 UTC, iamrajiv commented on C/cp/sum of triplet.c
> +/* Time Complexity of sort function : O(n^2)
@akanksha-saini add comments after this `/*`. Also, add space complexity.

2020-08-21 17:50 UTC, iamrajiv approved these changes
@akanksha-saini LGTM! Nice work.

2020-08-21 17:57 UTC, siddharth25pandey requested changes
@akanksha-saini Do the required changes

2020-08-21 17:57 UTC, siddharth25pandey commented on C/cp/sum of triplet.c
> +void sort(int a[1000], int n)
Take dynamic size array

2020-08-21 17:57 UTC, siddharth25pandey commented on C/cp/sum of triplet.c
> +void tripletSum(int a[1000], int n, int target)
Do the same, just write **int a[]**

2020-08-21 17:57 UTC, siddharth25pandey commented on C/cp/sum of triplet.c
> +	int a[1000], n, i, target;
Declare the array size after taking input from the user.
i.e **int a[n]**

2020-08-21 18:58 UTC, akanksha-saini commented
Please review now @siddharth25pandey , I have made the requested changes.

2020-08-21 19:02 UTC, siddharth25pandey requested changes

2020-08-21 19:02 UTC, siddharth25pandey commented on C/cp/sum of triplet.c
> +	a = (int)malloc(n * sizeof(int)); // take dynamic array as they are not of fixed size and are allocated on heap
here, do the changes,
a=(int*)malloc

2020-08-21 19:08 UTC, siddharth25pandey commented
@akanksha-saini Without using **stdlib** header how you are using malloc & allocating the memory in heap??
First run your Program, than try to submit the PR for review.
You can do either of two
*  **int a[n]** by defining n above this line **OR**
* **use Dynamic Memory allocation** by including standard Library

2020-08-21 19:21 UTC, akanksha-saini commented
I have committed changes to the file @siddharth25pandey

2020-08-21 19:50 UTC, siddharth25pandey approved these changes
@akanksha-saini Looks fine to me
Able to merge
Thanks!

2020-08-22 05:43 UTC, akanksha-saini commented
Please review my pull request @SKAUL05

2020-08-22 05:45 UTC, SKAUL05 approved these changes

2020-08-22 05:45 UTC, merged

2020-08-23 22:20 UTC, iamrajiv commented
@all-contributors please add @akanksha-saini for code