DP based C program to find minimum operations required to convert one string to other string.
TesseractCoding/NeoAlgo pull request #660
Opened 2020-08-21 11:58 UTC by nutanaarohi123

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
YES

### Description
#439 
 A Dynamic Programming based C program to find a minimum number of operations to convert string1 to string2.
**Time Complexity** :  O(mn)
**Space Complexity**:  O(mn)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#439

2020-08-21 12:09 UTC, iamrajiv requested changes
@nutanaarohi123 add time and space complexity at the end of the file.

2020-08-21 12:09 UTC, iamrajiv commented on C/dp/EditDistanceDP.c
> +/* A Dynamic Programming based C program to find minimum
@nutanaarohi123 format like this 
```
/* 
A Dynamic Programming based C program to find the minimum 
number operations to convert string1 to string2 
*/
```
Also, break line after this

2020-08-21 12:09 UTC, iamrajiv commented on C/dp/EditDistanceDP.c
> +/* Input:
@nutanaarohi123 format like this
```
/*
 Input:
Enter the first string: "Sunday"
Enter the second string: "Saturday"
Output: 3  
*/
```

2020-08-21 12:11 UTC, iamrajiv commented
@nutanaarohi123 remove `InterpolationSearch.java` file it's not related to this PR.

2020-08-21 12:25 UTC, nutanaarohi123 commented
Updated EditDistanceDP.c file and made changes as required. Removed the Interpolation java file.
Kindly review @iamrajiv

2020-08-21 12:32 UTC, iamrajiv requested changes
@nutanaarohi123 add time and space complexity

2020-08-21 12:32 UTC, iamrajiv commented on C/README.md
> +- [EditDistance in Dp](dynamicprogram/EditDistanceDP.c)
@nutanaarohi123 wrong URL added. Update this to `- [EditDistance in Dp](dp/EditDistanceDP.c)`

2020-08-21 12:53 UTC, nutanaarohi123 commented on C/README.md
> +- [EditDistance in Dp](dynamicprogram/EditDistanceDP.c)
Updated README.md and added Time and space complexity in the description section. of the pull requests.
kindly review @iamrajiv

2020-08-21 18:04 UTC, iamrajiv requested changes

2020-08-21 18:04 UTC, iamrajiv commented on C/dp/EditDistanceDP.c
> +								dp[indexstr1 - 1][indexstr2 - 1]); // Replace
@nutanaarohi123 format the whole code using code formatter there is lot whitespaces and indentations

2020-08-21 22:27 UTC, nutanaarohi123 commented on C/dp/EditDistanceDP.c
> +								dp[indexstr1 - 1][indexstr2 - 1]); // Replace
Updated the code and made changes as required. Kindly review @iamrajiv

2020-08-22 06:10 UTC, Kajol-Kumari approved these changes
Functionality working Fine! Well formatted and it's good to go :)

2020-08-22 06:56 UTC, SKAUL05 approved these changes
Well documented @nutanaarohi123 . Good to go :)

2020-08-22 08:09 UTC, iamrajiv approved these changes

2020-08-22 08:09 UTC, merged

2020-08-23 22:20 UTC, iamrajiv commented
@all-contributors please add @nutanaarohi123 for code